### ISSUE TITLE
crayon dependency

### ISSUE THREAD

**Issue by krlmlr** [spsanderson/TidyDensity#30]
**Describe the bug**

The dev version of pillar no longer imports the crayon package, coloring is now provided via the cli package. Please change to conditional use of crayon or switch to cli.

**To Reproduce**

Install the development version of pillar, and TidyDensity, into a clean library, try to load the package.

**Comment by spsanderson** [comment]
I don't use pillar instead I import crayon and cli

**Comment by krlmlr** [comment]
This package has crayon in "Suggests" but seems to use it unconditionally. This worked before because crayon was available via tibble -> pillar -> crayon, now this is no longer true.

Could you please switch to conditional usage, or move crayon to "Imports" (or avoid using crayon in favor of cli)?

**Comment by spsanderson** [comment]
Understood 

Sent from my iPhone
www.spsanderson.com
